"""Initial schema

Revision ID: 501dff028c29
Revises: 
Create Date: 2025-05-18 07:29:04.803475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '501dff028c29'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_azure_object_id', table_name='user')
    op.drop_index('ix_user_email', table_name='user')
    op.drop_table('user')
    op.drop_index('ix_role_name', table_name='role')
    op.drop_table('role')
    op.drop_table('rolepermission')
    op.drop_index('ix_permission_name', table_name='permission')
    op.drop_table('permission')
    op.drop_table('userrole')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userrole',
    sa.Column('user_id', sa.CHAR(length=32), nullable=False),
    sa.Column('role_id', sa.CHAR(length=32), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('permission',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_permission_name', 'permission', ['name'], unique=False)
    op.create_table('rolepermission',
    sa.Column('role_id', sa.CHAR(length=32), nullable=False),
    sa.Column('permission_id', sa.CHAR(length=32), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permission.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('role',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_role_name', 'role', ['name'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=False),
    sa.Column('full_name', sa.VARCHAR(), nullable=True),
    sa.Column('azure_object_id', sa.VARCHAR(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('is_superuser', sa.BOOLEAN(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_email', 'user', ['email'], unique=1)
    op.create_index('ix_user_azure_object_id', 'user', ['azure_object_id'], unique=1)
    # ### end Alembic commands ###
